# Generated by Django 2.2.4 on 2019-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourseFrom', models.CharField(max_length=100)),
                ('SenstiKind', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Warning',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
